# Generated automatically from Makefile.in by configure.
MANDIR	= /usr/local/man
MANSUB	= man8/

all:
install:
	install -c tinyproxy.8 ${MANDIR}/${MANSUB}
uninstall:
	rm -f ${MANDIR}/${MANSUB}/tinyproxy.8
